import { parse as parseHTML, type HTMLElement } from "node-html-parser";

const gradescopeOrigin = "https://www.gradescope.com";
const uploadHostPattern =
  /^production-gradescope-uploads\.s3(?:[.-][a-z0-9-]+)?\.amazonaws\.com$/i;
const pdfPathPattern = /^\/uploads\/pdf_attachment\/file\/\d+\/[^/]+\.pdf$/i;
const signedUrlParameters = [
  "X-Amz-Algorithm",
  "X-Amz-Credential",
  "X-Amz-Date",
  "X-Amz-Expires",
  "X-Amz-Signature",
  "X-Amz-SignedHeaders",
];

export interface AssignmentPdfLink {
  url: string;
  filename: string;
}

function normalizedText(element: HTMLElement): string {
  return (element.textContent ?? "").replace(/\s+/g, " ").trim();
}

function submissionFormPath(
  element: HTMLElement,
  courseId: string,
  assignmentId: string
): boolean {
  const action = element.getAttribute("action");
  if (!action) return false;

  try {
    const url = new URL(action, gradescopeOrigin);
    return (
      url.origin === gradescopeOrigin &&
      url.pathname ===
        `/courses/${courseId}/assignments/${assignmentId}/submissions`
    );
  } catch {
    return false;
  }
}

function filenameFromPath(pathname: string, assignmentId: string): string {
  const rawName = pathname.split("/").pop() ?? "";
  try {
    const decoded = decodeURIComponent(rawName);
    if (/^[^\\/\0\r\n]+\.pdf$/i.test(decoded)) return decoded;
  } catch {
    // Fall through to a safe deterministic name for malformed paths.
  }
  return `assignment-${assignmentId}.pdf`;
}

function parseAllowedPdfLink(
  anchor: HTMLElement,
  assignmentId: string
): AssignmentPdfLink | null {
  const label = normalizedText(anchor);
  if (!/download.*pdf/i.test(label)) return null;

  const href = anchor.getAttribute("href");
  if (!href) return null;

  try {
    const url = new URL(href, gradescopeOrigin);
    if (
      url.protocol !== "https:" ||
      !uploadHostPattern.test(url.hostname) ||
      !pdfPathPattern.test(url.pathname)
    ) {
      return null;
    }

    if (!signedUrlParameters.every((parameter) => url.searchParams.has(parameter))) {
      return null;
    }

    return {
      url: url.toString(),
      filename: filenameFromPath(url.pathname, assignmentId),
    };
  } catch {
    return null;
  }
}

/**
 * Find the fresh, assignment-specific Gradescope PDF link without returning
 * the signed URL to callers. The link lives in the submission form modal on
 * the student course dashboard and is regenerated by Gradescope over time.
 */
export function parseAssignmentPdfLink(
  html: string,
  courseId: string,
  assignmentId: string
): AssignmentPdfLink | null {
  const root = parseHTML(html);
  const form = root
    .querySelectorAll("form[action]")
    .find((candidate) =>
      submissionFormPath(candidate, courseId, assignmentId)
    );

  if (!form) return null;

  for (const anchor of form.querySelectorAll("a[href]")) {
    const link = parseAllowedPdfLink(anchor, assignmentId);
    if (link) return link;
  }

  return null;
}
