import { parse as parseHTML, type HTMLElement } from "node-html-parser";

const gradescopeOrigin = "https://www.gradescope.com";
const uploadHostPattern =
  /^production-gradescope-uploads\.s3(?:[.-][a-z0-9-]+)?\.amazonaws\.com$/i;
const pdfPathPattern = /^\/uploads\/pdf_attachment\/file\/\d+\/[^/]+\.pdf$/i;
const signedUrlParameters = [
  "X-Amz-Algorithm",
  "X-Amz-Credential",
  "X-Amz-Date",
  "X-Amz-Expires",
  "X-Amz-Signature",
  "X-Amz-SignedHeaders",
];

export interface AssignmentPdfLink {
  url: string;
  filename: string;
}

function normalizedText(element: HTMLElement): string {
  return (element.textContent ?? "").replace(/\s+/g, " ").trim();
}

function submissionFormPath(
  element: HTMLElement,
  courseId: string,
  assignmentId: string
): boolean {
  const action = element.getAttribute("action");
  if (!action) return false;

  try {
    const url = new URL(action, gradescopeOrigin);
    return (
      url.origin === gradescopeOrigin &&
      url.pathname ===
        `/courses/${courseId}/assignments/${assignmentId}/submissions`
    );
  } catch {
    return false;
  }
}

function filenameFromPath(pathname: string, assignmentId: string): string {
  const rawName = pathname.split("/").pop() ?? "";
  try {
    const decoded = decodeURIComponent(rawName);
    if (/^[^\\/\0\r\n]+\.pdf$/i.test(decoded)) return decoded;
  } catch {
    // Fall through to a safe deterministic name for malformed paths.
  }
  return `assignment-${assignmentId}.pdf`;
}

function parseAllowedPdfUrl(
  href: string | null | undefined,
  assignmentId: string
): AssignmentPdfLink | null {
  if (!href) return null;

  try {
    const url = new URL(href, gradescopeOrigin);
    if (
      url.protocol !== "https:" ||
      !uploadHostPattern.test(url.hostname) ||
      !pdfPathPattern.test(url.pathname)
    ) {
      return null;
    }

    if (!signedUrlParameters.every((parameter) => url.searchParams.has(parameter))) {
      return null;
    }

    return {
      url: url.toString(),
      filename: filenameFromPath(url.pathname, assignmentId),
    };
  } catch {
    return null;
  }
}

function parseAllowedPdfLink(
  anchor: HTMLElement,
  assignmentId: string
): AssignmentPdfLink | null {
  if (!/download.*pdf/i.test(normalizedText(anchor))) return null;
  return parseAllowedPdfUrl(anchor.getAttribute("href"), assignmentId);
}

function assignmentButtonId(element: HTMLElement): string | null {
  for (const attribute of [
    "data-assignment-id",
    "data-assignment_id",
    "data-assignment",
  ]) {
    const value = element.getAttribute(attribute)?.trim();
    if (value) return value;
  }
  return null;
}

/**
 * Find the fresh, assignment-specific Gradescope PDF link without returning
 * the signed URL to callers. Current student dashboards place it in the
 * assignment button's data-template-url attribute. Older markup may instead
 * expose a download anchor in the submission form modal, so that remains a
 * fallback. The URL is regenerated by Gradescope over time.
 */
export function parseAssignmentPdfLink(
  html: string,
  courseId: string,
  assignmentId: string
): AssignmentPdfLink | null {
  const root = parseHTML(html);

  const assignmentButton = root
    .querySelectorAll(
      "[data-assignment-id], [data-assignment_id], [data-assignment]"
    )
    .find((candidate) => assignmentButtonId(candidate) === assignmentId);
  const templateLink = parseAllowedPdfUrl(
    assignmentButton?.getAttribute("data-template-url"),
    assignmentId
  );
  if (templateLink) return templateLink;

  const form = root
    .querySelectorAll("form[action]")
    .find((candidate) =>
      submissionFormPath(candidate, courseId, assignmentId)
    );

  if (!form) return null;

  // Gradescope currently renders the instructional paragraph containing the
  // PDF link as a sibling of the upload form inside the same dialog, rather
  // than as a descendant of the form itself.
  const container = form.closest("dialog") ?? form;
  for (const anchor of container.querySelectorAll("a[href]")) {
    const link = parseAllowedPdfLink(anchor, assignmentId);
    if (link) return link;
  }

  return null;
}
